title: "Hisao Portfolio"
description: "Python・自動化・データ分析の学びと作品"
url: "https://go-pro-world.net"
baseurl: ""

# Minimal Mistakes を外部から読み込む設定
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Hisao"
  email: "yourname@example.com"

header_pages:
  - index.md
  - about.md
  - contact.md

title_separator: "｜"
show_excerpts: true
excerpt_separator: "<!--more-->"
markdown: kramdown
kramdown:
  input: GFM
